# Site settings
title: STRoNA
name: STRoNA
email: gihyun.lim@manchester.ac.uk  
description: "Spatio-Temporal Representation on Neuromorphic Architecture"
url:  https://strona-mscaz.github.io/

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503 
  secondary-dark: 000

# forJekyll-Scholar configuration
scholar:
    bibliography_template: bib
    # bibliography_template: bibtemplate

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
academi:
  - title: google-scholar
    url: https://scholar.google.co.uk/citations?user=cND1p2oAAAAJ 
social:
  - title: envelope
    url: mailto:gihyun.lim@manchester.ac.uk
  - title: github
    url: http://github.com/ghlim

# Postal address (add as many lines as necessary)
address:
  - line: Kilburn Building
  - line: University of Manchester
  - line: Manchester M13 9PL, UK

# RSS feed
plugins:
  - jekyll-feed

# Build settings
markdown: GFM
permalink: pretty
